M48
; DRILL file {KiCad 9.0.7} date 2026-03-12T14:59:16-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-12T14:59:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X142.24Y-135.89
T2
X138.43Y-59.69
X143.51Y-59.69
M30
